version: '3.5'

services:
  postgres:
    networks:
      multitenant:
        aliases:
          - db-server
    environment:
      POSTGRES_DB: wellsky
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
       context: ./postgresql
       dockerfile: ./postgres.Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5998:5432"
    restart: always
  multitenantapi:
    image: ${DOCKER_REGISTRY-}multitenantapi
    networks:
      multitenant:
        aliases:
          - api-server
    build:
      context: .
      dockerfile: tenantPOC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=44340
      - TENANTS_DB_SERVER=db-server
      - TENANTS_DB_PORT=5432
      - TENANTS_DB_USER=postgres
      - TENANTS_DB_PASSWORD=postgres
      - TENANTS_DATABASE=wellskyqa
      - LOGS_PATH=/var/log/
      - LOGS_FILE_NAME=openreferrals
    ports:
      - "51240:80"
      - "44340:443"  
  odataapi:
    image: ${DOCKER_REGISTRY-}odataapi
    networks:
      multitenant:
        aliases:
          - odata-server
    build:
      context: .
      dockerfile: odataAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - TENANTS_DB_SERVER=db-server
      - TENANTS_DB_PORT=5432
      - TENANTS_DB_USER=postgres
      - TENANTS_DB_PASSWORD=postgres
      - TENANTS_DATABASE=wellskyqa
      - LOGS_PATH=/var/log/
      - LOGS_FILE_NAME=openreferrals
    ports:
      - "53275:80"
      - "43389:443"  
networks:
  multitenant:
    external: false
    name: multitenant-network
volumes:
  postgres-data:
    name: multitenant-postgres-volume